#!/usr/bin/env bash
echo "== deploy  with CFN"

# Variables
STACK_NAME="Athena-Federation-Workshop"
TEMPLATE_FILE="Athena-Federation-Workshop.yaml"


aws cloudformation deploy \
  --template-file $TEMPLATE_FILE \
  --stack-name $STACK_NAME \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND